# Generated by Django 5.2.4 on 2025-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian')], default='student', max_length=10),
        ),
    ]
