# Generated by Django 5.2.4 on 2025-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitylibrary', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=50),
        ),
    ]
